[package]
name = "colorgrad"
version = "0.6.1"
authors = ["Nor Khasyatillah <mazznoer@ymail.com>"]
edition = "2018"
description = "Color scales library for data visualization, charts, games, generative art and others."
readme = "README.md"
repository = "https://github.com/mazznoer/colorgrad-rs"
documentation = "https://docs.rs/colorgrad/"
license = "MIT OR Apache-2.0"
keywords = ["color", "colormap", "color-scales", "visualization", "gradient"]
categories = ["graphics", "visualization"]
exclude = [
	".github/*",
	".gitignore",
	"docs/*",
	"example_output/*",
]

[dependencies]
csscolorparser = { version = "0.6.2", default-features = false }

[features]
default = ["named-colors"]
named-colors = ["csscolorparser/named-colors"]

[dev-dependencies]
criterion = { version = "0.3.6", features = ["html_reports"] }
image = { version = "0.24.3", default-features = false, features = ["png"] }

[[bench]]
name = "custom_gradient"
harness = false

[[bench]]
name = "preset"
harness = false

[[bench]]
name = "gimp"
harness = false
