[package]
name = "colorgrad"
version = "0.1.0"
authors = ["Nor Khasyatillah <mazznoer@ymail.com>"]
edition = "2018"
description = "Rust color scales library for charts, maps, data visualization and creative coding."
readme = "README.md"
repository = "https://github.com/mazznoer/colorgrad-rs"
documentation = "https://docs.rs/colorgrad/"
license = "MIT OR Apache-2.0"
keywords = ["color", "colormap", "color-scales", "scheme", "gradient"]
categories = ["graphics"]
exclude = [
	".github/*",
	".travis.yml",
	"docs/*",
	"examples/*",
	"tests/*",
]

[dependencies]
csscolorparser = "0.2.0"

[dev-dependencies]
image = "0.23.12"
noise = "0.6.0"

