[package]
name = "colorgrad"
version = "0.4.0"
authors = ["Nor Khasyatillah <mazznoer@ymail.com>"]
edition = "2018"
description = "Color scales library for data visualization, charts, games, generative art and others."
readme = "README.md"
repository = "https://github.com/mazznoer/colorgrad-rs"
documentation = "https://docs.rs/colorgrad/"
license = "MIT OR Apache-2.0"
keywords = ["color", "colormap", "color-scales", "visualization", "gradient"]
categories = ["graphics"]
exclude = [
	".github/*",
	".gitignore",
	".travis.yml",
	"docs/*",
	"examples/*",
	"example_output/*",
	"tests/*",
]

[dependencies]
csscolorparser = "0.4.0"

[dev-dependencies]
image = { version = "0.23.14", default-features = false, features = ["png"] }

